[tool.poetry]
name = "minisd"
version = "0.1.0"
description = ""
authors = ["__mo_san__ <moboustt@student.1337.ma>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
